# This is a basic workflow to help you get started with Actions

# To use spesific terraform version !!!
  
#    - name: Install Terraform
#      env:
#            TERRAFORM_VERSION: "0.12.15"
#      run: |
#        tf_version=$TERRAFORM_VERSION
#        wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
#        unzip terraform_"$tf_version"_linux_amd64.zip
#        sudo mv terraform /usr/local/bin/

  
name: terraform_for_pull_reguests

on:
#  push:
#    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Terraform version
        run: terraform --version
      
      - name: Git clone repo
        uses: actions/checkout@v1
        
      - name: Show all file
        run: ls -la
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
        
      - name: Terraform init
        id: init
        run: cd ./terraform && terraform init
        
      - name: Terraform Plan
        id: plan
        run: cd ./terraform && terraform plan
        
      - name: Terraform Destroy
        id: destroy-1
        run: cd ./terraform && terraform destroy -auto-approve
      
      - name: Terraform Apply
        id: apply
        run: cd ./terraform && terraform apply -auto-approve
        
      - name: Terraform Destroy
        id: destroy-2
        run: cd ./terraform && terraform destroy -auto-approve
