# This is a basic workflow to help you get started with Actions

# To use spesific terraform version !!!
  
#    - name: Install Terraform
#      env:
#            TERRAFORM_VERSION: "0.12.15"
#      run: |
#        tf_version=$TERRAFORM_VERSION
#        wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
#        unzip terraform_"$tf_version"_linux_amd64.zip
#        sudo mv terraform /usr/local/bin/

  
name: terraform_for_pull_reguests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
#  push:
#    branches: [ master ]
  pull_request:
    branches: [ master ]

  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Terraform version
        run: terraform --version
      
      - name: Git clone repo
        uses: actions/checkout@v1
        
      - name: Show all file
        run: ls -la
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
        
      - name: Terraform init
        id: init
        run: cd ./terraform && terraform init
        
      - name: Terraform Plan
        id: plan
        run: cd ./terraform && terraform plan
