name: pull

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: autero1/action-terraform@v0.1.0
        with:
          terraform_version: 0.12.24
      
      - name: Git clone repo
        uses: actions/checkout@v1
        
      - name: Terraform init
        run: terraform init
      
      - name: Terraform validate
        run: terraform validate
        
      - name: Terraform Plan
        run: terraform plan